# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - uses: microsoft/setup-msbuild@v1.0.0
    - uses: nuget/setup-nuget@v1
    - run: nuget restore HorseWander.sln
    - run: msbuild HorseWander.sln /p:Configuration=Release

    - uses: actions/upload-artifact@v2
      with:
        name: build
        path: HorseWander\bin\Release
